title: Daniel de Abreu Pereira Uhr
description: Professor de Economia na UFPel
url: "https://daniel-uhr.github.io"
baseurl: ""

theme: minima

header_pages:
  - index.md
  - research.md
  - cv.md
  - contact.md

