title: Daniel de Abreu Pereira Uhr
description: Professor de Economia na UFPel
url: "https://daniel-uhr.github.io"
baseurl: ""

# Tema remoto
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme # Permite usar temas remotos

# Configuração de navegação
header_pages:
  - index.md
  - research.md
  - cv.md
  - contact.md

# Informações adicionais
author:
  name: Daniel de Abreu Pereira Uhr
  avatar: "/assets/images/daniel.jpeg"
  bio: "Professor de Economia na Universidade Federal de Pelotas (UFPel)."
  location: "Pelotas, RS, Brasil"
  email: daniel.uhr@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Daniel-Uhr"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/daniel-uhr-6847675b"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/danieluhr01"
